#!/bin/bash
E=mc2theory$

if [[ "${UID}" -eq 0 ]]
then
	echo "You are the root"
	read -p "Username: " USER_NAME
	read -p "Name: " NAME
	read -p "Initial Password: " PASSWORD

	# Create the user

	useradd -c "for ${NAME}, Auto generated by User ${UID} using add-local-user.sh" "${USER_NAME}"

	if [[ "${?}" -ne 0 ]]
	then
		echo "User could not be added"
		exit 1
	fi

	# Set password

	echo ${PASSWORD} | passwd --stdin ${USER_NAME}

	if [[ "${?}" -ne 0 ]]
	then
		echo "The password for the user could not be set."
		exit 1
	fi

	# Force password change on first login

	passwd -e ${USER_NAME}

	echo

	# Display the username, password, and the host

	echo "User ${NAME} with username ${USER_NAME} was created with password ${PASSWORD} at host ${HOST}"
	exit 0
else
	echo "Requires root access to run this script"
	exit 1
fi